services:
  - type: web
    name: knight-bot-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"